import Head from "next/head";

import { Game } from "../components";

export default function Home() {
  const a = 3;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Game />
      </main>
    </div>
  );
}
