import Head from "next/head";

import NonSSRWrapper from "../components/NonSSRWrapper";
import { Root } from "../components/Root";

export default function Home() {
  return (
    // TODO: figure out needness of this wrapper
    <NonSSRWrapper>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Root />
        </main>
      </div>
    </NonSSRWrapper>
  );
}
